[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E02B96E4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/50c16619112629352644b2a6c55a43c9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E02B96E390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/50c16619112629352644b2a6c55a43c9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E02B96E5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/50c16619112629352644b2a6c55a43c9